-- =========================================================================
-- SCRIPT DDL COMPLETO - SkillRise 2030+
-- Descrição: Schema completo do banco de dados Oracle
-- Versão: 3.0 (Completo com Sistema de Vagas)
-- Data: 2025
-- =========================================================================
-- Este script cria:
-- - 17 sequences para auto-incremento
-- - 17 tabelas (sistema completo + vagas/oportunidades)
-- - Triggers para auto-incremento de IDs
-- - Foreign Keys e constraints
-- - Índices para performance
-- - Views analíticas
-- =========================================================================

-- =========================================================================
-- SEQUENCES (17 no total)
-- =========================================================================
CREATE SEQUENCE TB_USER_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_SKILL_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_USER_SKILL_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_TRILHA_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_MODULO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_TRILHA_MODULO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_INSCRICAO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_PROGRESSO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_EMPRESA_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_OPORTUNIDADE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_TRILHA_OPORTUNIDADE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_RECOMENDACAO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_CERTIFICADO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_ACHIEVEMENT_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_NOTIFICACAO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE TB_META_ID_SEQ START WITH 1 NOCACHE ORDER;
/

-- =========================================================================
-- TABELA 1: TB_USER (Usuários da Plataforma)
-- =========================================================================
CREATE TABLE TB_USER
(
  USER_ID        NUMBER(10) NOT NULL,
  NAME           VARCHAR2(200) NOT NULL,
  EMAIL          VARCHAR2(200) NOT NULL,
  PASSWORD       VARCHAR2(255) NOT NULL,
  ROLE           VARCHAR2(50)  NOT NULL,
  BIRTH_DATE     DATE,
  CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
  -- Campos de gamificação
  XP             NUMBER(10) DEFAULT 0,
  LEVEL_ACCOUNT  NUMBER(5) DEFAULT 1,
  STREAK_DIAS    NUMBER(5) DEFAULT 0,
  ULTIMO_ACESSO  DATE
)
;

COMMENT ON TABLE TB_USER IS 'Tabela de usuários da plataforma';
COMMENT ON COLUMN TB_USER.USER_ID IS 'ID do usuário';
COMMENT ON COLUMN TB_USER.NAME IS 'Nome completo do usuário';
COMMENT ON COLUMN TB_USER.EMAIL IS 'E-mail do usuário (identificador único)';
COMMENT ON COLUMN TB_USER.PASSWORD IS 'Senha hasheada do usuário';
COMMENT ON COLUMN TB_USER.ROLE IS 'Papel: USER ou ADMIN';
COMMENT ON COLUMN TB_USER.BIRTH_DATE IS 'Data de nascimento';
COMMENT ON COLUMN TB_USER.CREATED_AT IS 'Data de criação do registro';
COMMENT ON COLUMN TB_USER.XP IS 'Pontos de experiência do usuário';
COMMENT ON COLUMN TB_USER.LEVEL_ACCOUNT IS 'Nível do usuário baseado em XP';
COMMENT ON COLUMN TB_USER.STREAK_DIAS IS 'Sequência de dias consecutivos ativos';
COMMENT ON COLUMN TB_USER.ULTIMO_ACESSO IS 'Último acesso do usuário à plataforma';

ALTER TABLE TB_USER ADD CONSTRAINT TB_USER_PK PRIMARY KEY (USER_ID);

CREATE OR REPLACE TRIGGER TB_USER_ID_TRG
BEFORE INSERT ON TB_USER
FOR EACH ROW
WHEN (NEW.USER_ID IS NULL)
BEGIN
  :NEW.USER_ID := TB_USER_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 2: TB_SKILL (Competências/Habilidades)
-- =========================================================================
CREATE TABLE TB_SKILL
(
  SKILL_ID    NUMBER(10) NOT NULL,
  NAME        VARCHAR2(150) NOT NULL,
  DESCRIPTION VARCHAR2(4000)
)
;

COMMENT ON TABLE TB_SKILL IS 'Tabela de competências/habilidades';
COMMENT ON COLUMN TB_SKILL.SKILL_ID IS 'ID da skill';
COMMENT ON COLUMN TB_SKILL.NAME IS 'Nome da competência';
COMMENT ON COLUMN TB_SKILL.DESCRIPTION IS 'Descrição da competência';

ALTER TABLE TB_SKILL ADD CONSTRAINT TB_SKILL_PK PRIMARY KEY (SKILL_ID);

CREATE OR REPLACE TRIGGER TB_SKILL_ID_TRG
BEFORE INSERT ON TB_SKILL
FOR EACH ROW
WHEN (NEW.SKILL_ID IS NULL)
BEGIN
  :NEW.SKILL_ID := TB_SKILL_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 3: TB_USER_SKILL (Relação Usuário-Skill com Proficiência)
-- =========================================================================
CREATE TABLE TB_USER_SKILL
(
  USER_SKILL_ID     NUMBER(10) NOT NULL,
  USER_ID           NUMBER(10) NOT NULL,
  SKILL_ID          NUMBER(10) NOT NULL,
  PROFICIENCY_LEVEL NUMBER(3) DEFAULT 0,
  CREATED_AT        DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_USER_SKILL IS 'Relação entre usuário e skills com proficiência';
COMMENT ON COLUMN TB_USER_SKILL.USER_SKILL_ID IS 'ID do vínculo usuário-skill';
COMMENT ON COLUMN TB_USER_SKILL.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_USER_SKILL.SKILL_ID IS 'FK para TB_SKILL.SKILL_ID';
COMMENT ON COLUMN TB_USER_SKILL.PROFICIENCY_LEVEL IS 'Nível de proficiência (0-100)';
COMMENT ON COLUMN TB_USER_SKILL.CREATED_AT IS 'Data de criação do vínculo';

ALTER TABLE TB_USER_SKILL ADD CONSTRAINT TB_USER_SKILL_PK PRIMARY KEY (USER_SKILL_ID);

ALTER TABLE TB_USER_SKILL
  ADD CONSTRAINT TB_USER_SKILL_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

ALTER TABLE TB_USER_SKILL
  ADD CONSTRAINT TB_USER_SKILL_TB_SKILL_FK FOREIGN KEY (SKILL_ID)
  REFERENCES TB_SKILL (SKILL_ID)
;

CREATE OR REPLACE TRIGGER TB_USER_SKILL_ID_TRG
BEFORE INSERT ON TB_USER_SKILL
FOR EACH ROW
WHEN (NEW.USER_SKILL_ID IS NULL)
BEGIN
  :NEW.USER_SKILL_ID := TB_USER_SKILL_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 4: TB_TRILHA (Trilhas de Aprendizagem)
-- =========================================================================
CREATE TABLE TB_TRILHA
(
  TRILHA_ID         NUMBER(10) NOT NULL,
  TITLE             VARCHAR2(300) NOT NULL,
  DESCRIPTION       CLOB,
  DIFFICULTY        VARCHAR2(50),
  DURATION_HOURS    NUMBER(6,2),
  CREATED_AT        DATE DEFAULT SYSDATE NOT NULL,
  -- Campos adicionais
  TAGS              VARCHAR2(500),
  RATING            NUMBER(3,2) DEFAULT 0.0,
  TOTAL_AVALIACOES  NUMBER(10) DEFAULT 0,
  CATEGORIA         VARCHAR2(100),
  IMAGE_URL         VARCHAR2(500)
)
;

COMMENT ON TABLE TB_TRILHA IS 'Trilhas / cursos estruturados da plataforma';
COMMENT ON COLUMN TB_TRILHA.TRILHA_ID IS 'ID da trilha';
COMMENT ON COLUMN TB_TRILHA.TITLE IS 'Título da trilha';
COMMENT ON COLUMN TB_TRILHA.DESCRIPTION IS 'Descrição completa da trilha';
COMMENT ON COLUMN TB_TRILHA.DIFFICULTY IS 'Nível de dificuldade';
COMMENT ON COLUMN TB_TRILHA.DURATION_HOURS IS 'Duração estimada em horas';
COMMENT ON COLUMN TB_TRILHA.CREATED_AT IS 'Data de criação';
COMMENT ON COLUMN TB_TRILHA.TAGS IS 'Tags separadas por vírgula (ex: machine-learning,python,ai)';
COMMENT ON COLUMN TB_TRILHA.RATING IS 'Avaliação média (0.0 a 5.0)';
COMMENT ON COLUMN TB_TRILHA.TOTAL_AVALIACOES IS 'Número total de avaliações';
COMMENT ON COLUMN TB_TRILHA.CATEGORIA IS 'Categoria: TECNOLOGIA, SOFT_SKILLS, NEGOCIOS, etc';
COMMENT ON COLUMN TB_TRILHA.IMAGE_URL IS 'URL da imagem da trilha';

ALTER TABLE TB_TRILHA ADD CONSTRAINT TB_TRILHA_PK PRIMARY KEY (TRILHA_ID);

CREATE OR REPLACE TRIGGER TB_TRILHA_ID_TRG
BEFORE INSERT ON TB_TRILHA
FOR EACH ROW
WHEN (NEW.TRILHA_ID IS NULL)
BEGIN
  :NEW.TRILHA_ID := TB_TRILHA_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 5: TB_MODULO (Módulos de Conteúdo)
-- =========================================================================
CREATE TABLE TB_MODULO
(
  MODULO_ID        NUMBER(10) NOT NULL,
  TITLE            VARCHAR2(300) NOT NULL,
  DURATION_MINUTES NUMBER(6),
  CONTENT_TYPE     VARCHAR2(50),
  CREATED_AT       DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_MODULO IS 'Módulos que compõem trilhas';
COMMENT ON COLUMN TB_MODULO.MODULO_ID IS 'ID do módulo';
COMMENT ON COLUMN TB_MODULO.TITLE IS 'Título do módulo';
COMMENT ON COLUMN TB_MODULO.DURATION_MINUTES IS 'Duração estimada em minutos';
COMMENT ON COLUMN TB_MODULO.CONTENT_TYPE IS 'Tipo de conteúdo (video, leitura, simulacao)';
COMMENT ON COLUMN TB_MODULO.CREATED_AT IS 'Data de criação';

ALTER TABLE TB_MODULO ADD CONSTRAINT TB_MODULO_PK PRIMARY KEY (MODULO_ID);

CREATE OR REPLACE TRIGGER TB_MODULO_ID_TRG
BEFORE INSERT ON TB_MODULO
FOR EACH ROW
WHEN (NEW.MODULO_ID IS NULL)
BEGIN
  :NEW.MODULO_ID := TB_MODULO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 6: TB_TRILHA_MODULO (Associação Trilha-Módulo)
-- =========================================================================
CREATE TABLE TB_TRILHA_MODULO
(
  TRILHA_MODULO_ID NUMBER(10) NOT NULL,
  TRILHA_ID        NUMBER(10) NOT NULL,
  MODULO_ID        NUMBER(10) NOT NULL,
  MODULE_ORDER     NUMBER(5) DEFAULT 1
)
;

COMMENT ON TABLE TB_TRILHA_MODULO IS 'Associação entre trilhas e módulos com ordem';
COMMENT ON COLUMN TB_TRILHA_MODULO.TRILHA_MODULO_ID IS 'ID da associação trilha-modulo';
COMMENT ON COLUMN TB_TRILHA_MODULO.TRILHA_ID IS 'FK para TB_TRILHA.TRILHA_ID';
COMMENT ON COLUMN TB_TRILHA_MODULO.MODULO_ID IS 'FK para TB_MODULO.MODULO_ID';
COMMENT ON COLUMN TB_TRILHA_MODULO.MODULE_ORDER IS 'Ordem do módulo dentro da trilha';

ALTER TABLE TB_TRILHA_MODULO ADD CONSTRAINT TB_TRILHA_MODULO_PK PRIMARY KEY (TRILHA_MODULO_ID);

ALTER TABLE TB_TRILHA_MODULO
  ADD CONSTRAINT TB_TRILHA_MODULO_TB_TRILHA_FK FOREIGN KEY (TRILHA_ID)
  REFERENCES TB_TRILHA (TRILHA_ID)
;

ALTER TABLE TB_TRILHA_MODULO
  ADD CONSTRAINT TB_TRILHA_MODULO_TB_MODULO_FK FOREIGN KEY (MODULO_ID)
  REFERENCES TB_MODULO (MODULO_ID)
;

CREATE OR REPLACE TRIGGER TB_TRILHA_MODULO_ID_TRG
BEFORE INSERT ON TB_TRILHA_MODULO
FOR EACH ROW
WHEN (NEW.TRILHA_MODULO_ID IS NULL)
BEGIN
  :NEW.TRILHA_MODULO_ID := TB_TRILHA_MODULO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 7: TB_INSCRICAO (Inscrição de Usuário em Trilha)
-- =========================================================================
CREATE TABLE TB_INSCRICAO
(
  INSCRICAO_ID   NUMBER(10) NOT NULL,
  USER_ID        NUMBER(10) NOT NULL,
  TRILHA_ID      NUMBER(10) NOT NULL,
  DATA_INSCRICAO DATE DEFAULT SYSDATE NOT NULL,
  DATA_CONCLUSAO DATE,
  STATUS         VARCHAR2(50) DEFAULT 'EM_PROGRESSO'
)
;

COMMENT ON TABLE TB_INSCRICAO IS 'Inscrições de usuários nas trilhas';
COMMENT ON COLUMN TB_INSCRICAO.INSCRICAO_ID IS 'ID da inscrição';
COMMENT ON COLUMN TB_INSCRICAO.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_INSCRICAO.TRILHA_ID IS 'FK para TB_TRILHA.TRILHA_ID';
COMMENT ON COLUMN TB_INSCRICAO.DATA_INSCRICAO IS 'Data de inscrição na trilha';
COMMENT ON COLUMN TB_INSCRICAO.DATA_CONCLUSAO IS 'Data de conclusão (se aplicável)';
COMMENT ON COLUMN TB_INSCRICAO.STATUS IS 'Status: EM_PROGRESSO, CONCLUIDA, PAUSADA';

ALTER TABLE TB_INSCRICAO ADD CONSTRAINT TB_INSCRICAO_PK PRIMARY KEY (INSCRICAO_ID);

ALTER TABLE TB_INSCRICAO
  ADD CONSTRAINT TB_INSCRICAO_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

ALTER TABLE TB_INSCRICAO
  ADD CONSTRAINT TB_INSCRICAO_TB_TRILHA_FK FOREIGN KEY (TRILHA_ID)
  REFERENCES TB_TRILHA (TRILHA_ID)
;

CREATE OR REPLACE TRIGGER TB_INSCRICAO_ID_TRG
BEFORE INSERT ON TB_INSCRICAO
FOR EACH ROW
WHEN (NEW.INSCRICAO_ID IS NULL)
BEGIN
  :NEW.INSCRICAO_ID := TB_INSCRICAO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 8: TB_PROGRESSO (Progresso em Módulos)
-- =========================================================================
CREATE TABLE TB_PROGRESSO
(
  PROGRESSO_ID   NUMBER(10) NOT NULL,
  INSCRICAO_ID   NUMBER(10) NOT NULL,
  MODULO_ID      NUMBER(10) NOT NULL,
  PERCENTAGE     NUMBER(5,2) DEFAULT 0.0,
  COMPLETED_AT   DATE,
  LAST_UPDATED   DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_PROGRESSO IS 'Progresso detalhado por módulo de cada inscrição';
COMMENT ON COLUMN TB_PROGRESSO.PROGRESSO_ID IS 'ID do registro de progresso';
COMMENT ON COLUMN TB_PROGRESSO.INSCRICAO_ID IS 'FK para TB_INSCRICAO.INSCRICAO_ID';
COMMENT ON COLUMN TB_PROGRESSO.MODULO_ID IS 'FK para TB_MODULO.MODULO_ID';
COMMENT ON COLUMN TB_PROGRESSO.PERCENTAGE IS 'Percentual de conclusão (0.0 a 100.0)';
COMMENT ON COLUMN TB_PROGRESSO.COMPLETED_AT IS 'Data de conclusão do módulo';
COMMENT ON COLUMN TB_PROGRESSO.LAST_UPDATED IS 'Última atualização do progresso';

ALTER TABLE TB_PROGRESSO ADD CONSTRAINT TB_PROGRESSO_PK PRIMARY KEY (PROGRESSO_ID);

ALTER TABLE TB_PROGRESSO
  ADD CONSTRAINT TB_PROGRESSO_TB_INSCRICAO_FK FOREIGN KEY (INSCRICAO_ID)
  REFERENCES TB_INSCRICAO (INSCRICAO_ID)
;

ALTER TABLE TB_PROGRESSO
  ADD CONSTRAINT TB_PROGRESSO_TB_MODULO_FK FOREIGN KEY (MODULO_ID)
  REFERENCES TB_MODULO (MODULO_ID)
;

CREATE OR REPLACE TRIGGER TB_PROGRESSO_ID_TRG
BEFORE INSERT ON TB_PROGRESSO
FOR EACH ROW
WHEN (NEW.PROGRESSO_ID IS NULL)
BEGIN
  :NEW.PROGRESSO_ID := TB_PROGRESSO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 9: TB_EMPRESA (Empresas Parceiras)
-- =========================================================================
CREATE TABLE TB_EMPRESA
(
  EMPRESA_ID  NUMBER(10) NOT NULL,
  NAME        VARCHAR2(200) NOT NULL,
  WEBSITE     VARCHAR2(500),
  CREATED_AT  DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_EMPRESA IS 'Empresas parceiras que oferecem oportunidades';
COMMENT ON COLUMN TB_EMPRESA.EMPRESA_ID IS 'ID da empresa';
COMMENT ON COLUMN TB_EMPRESA.NAME IS 'Nome da empresa';
COMMENT ON COLUMN TB_EMPRESA.WEBSITE IS 'Website da empresa';
COMMENT ON COLUMN TB_EMPRESA.CREATED_AT IS 'Data de cadastro';

ALTER TABLE TB_EMPRESA ADD CONSTRAINT TB_EMPRESA_PK PRIMARY KEY (EMPRESA_ID);

CREATE OR REPLACE TRIGGER TB_EMPRESA_ID_TRG
BEFORE INSERT ON TB_EMPRESA
FOR EACH ROW
WHEN (NEW.EMPRESA_ID IS NULL)
BEGIN
  :NEW.EMPRESA_ID := TB_EMPRESA_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 10: TB_OPORTUNIDADE (Vagas/Oportunidades de Trabalho)
-- =========================================================================
CREATE TABLE TB_OPORTUNIDADE
(
  OPORTUNIDADE_ID  NUMBER(10) NOT NULL,
  EMPRESA_ID       NUMBER(10) NOT NULL,
  TITLE            VARCHAR2(300) NOT NULL,
  DESCRIPTION      VARCHAR2(500),
  REQUIRED_SKILLS  VARCHAR2(1000),
  POSTED_AT        DATE DEFAULT SYSDATE NOT NULL,
  SALARIO_MIN      NUMBER(10,2),
  SALARIO_MAX      NUMBER(10,2),
  NIVEL            VARCHAR2(50),
  LOCALIZACAO      VARCHAR2(200),
  TIPO_CONTRATO    VARCHAR2(50),
  STATUS           VARCHAR2(20) DEFAULT 'ATIVA'
)
;

COMMENT ON TABLE TB_OPORTUNIDADE IS 'Oportunidades de trabalho oferecidas pelas empresas';
COMMENT ON COLUMN TB_OPORTUNIDADE.OPORTUNIDADE_ID IS 'ID da oportunidade';
COMMENT ON COLUMN TB_OPORTUNIDADE.EMPRESA_ID IS 'FK para TB_EMPRESA.EMPRESA_ID';
COMMENT ON COLUMN TB_OPORTUNIDADE.TITLE IS 'Título da vaga';
COMMENT ON COLUMN TB_OPORTUNIDADE.DESCRIPTION IS 'Descrição completa da vaga';
COMMENT ON COLUMN TB_OPORTUNIDADE.REQUIRED_SKILLS IS 'Skills necessárias (separadas por vírgula)';
COMMENT ON COLUMN TB_OPORTUNIDADE.POSTED_AT IS 'Data de publicação da vaga';
COMMENT ON COLUMN TB_OPORTUNIDADE.SALARIO_MIN IS 'Salário mínimo oferecido';
COMMENT ON COLUMN TB_OPORTUNIDADE.SALARIO_MAX IS 'Salário máximo oferecido';
COMMENT ON COLUMN TB_OPORTUNIDADE.NIVEL IS 'Nível: Júnior, Pleno, Sênior';
COMMENT ON COLUMN TB_OPORTUNIDADE.LOCALIZACAO IS 'Localização da vaga';
COMMENT ON COLUMN TB_OPORTUNIDADE.TIPO_CONTRATO IS 'Tipo: CLT, PJ, Estágio';
COMMENT ON COLUMN TB_OPORTUNIDADE.STATUS IS 'Status: ATIVA, INATIVA, FECHADA';

ALTER TABLE TB_OPORTUNIDADE ADD CONSTRAINT TB_OPORTUNIDADE_PK PRIMARY KEY (OPORTUNIDADE_ID);

ALTER TABLE TB_OPORTUNIDADE
  ADD CONSTRAINT TB_OPORTUNIDADE_TB_EMPRESA_FK FOREIGN KEY (EMPRESA_ID)
  REFERENCES TB_EMPRESA (EMPRESA_ID)
;

CREATE OR REPLACE TRIGGER TB_OPORTUNIDADE_ID_TRG
BEFORE INSERT ON TB_OPORTUNIDADE
FOR EACH ROW
WHEN (NEW.OPORTUNIDADE_ID IS NULL)
BEGIN
  :NEW.OPORTUNIDADE_ID := TB_OPORTUNIDADE_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 11: TB_TRILHA_OPORTUNIDADE (Associação Trilha-Oportunidade)
-- =========================================================================
CREATE TABLE TB_TRILHA_OPORTUNIDADE
(
  TRILHA_OPORTUNIDADE_ID NUMBER(10) NOT NULL,
  TRILHA_ID              NUMBER(10) NOT NULL,
  OPORTUNIDADE_ID        NUMBER(10) NOT NULL,
  CRIADO_EM              DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_TRILHA_OPORTUNIDADE IS 'Associação entre trilhas e oportunidades de trabalho';
COMMENT ON COLUMN TB_TRILHA_OPORTUNIDADE.TRILHA_OPORTUNIDADE_ID IS 'ID da associação';
COMMENT ON COLUMN TB_TRILHA_OPORTUNIDADE.TRILHA_ID IS 'FK para TB_TRILHA.TRILHA_ID';
COMMENT ON COLUMN TB_TRILHA_OPORTUNIDADE.OPORTUNIDADE_ID IS 'FK para TB_OPORTUNIDADE.OPORTUNIDADE_ID';
COMMENT ON COLUMN TB_TRILHA_OPORTUNIDADE.CRIADO_EM IS 'Data de criação da associação';

ALTER TABLE TB_TRILHA_OPORTUNIDADE ADD CONSTRAINT TB_TRILHA_OPORTUNIDADE_PK PRIMARY KEY (TRILHA_OPORTUNIDADE_ID);

ALTER TABLE TB_TRILHA_OPORTUNIDADE
  ADD CONSTRAINT TB_TRILHA_OPP_TB_TRILHA_FK FOREIGN KEY (TRILHA_ID)
  REFERENCES TB_TRILHA (TRILHA_ID)
;

ALTER TABLE TB_TRILHA_OPORTUNIDADE
  ADD CONSTRAINT TB_TRILHA_OPP_TB_OPORT_FK FOREIGN KEY (OPORTUNIDADE_ID)
  REFERENCES TB_OPORTUNIDADE (OPORTUNIDADE_ID)
;

CREATE OR REPLACE TRIGGER TB_TRILHA_OPORTUNIDADE_ID_TRG
BEFORE INSERT ON TB_TRILHA_OPORTUNIDADE
FOR EACH ROW
WHEN (NEW.TRILHA_OPORTUNIDADE_ID IS NULL)
BEGIN
  :NEW.TRILHA_OPORTUNIDADE_ID := TB_TRILHA_OPORTUNIDADE_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 12: TB_RECOMENDACAO (Recomendações de IA)
-- =========================================================================
CREATE TABLE TB_RECOMENDACAO
(
  RECOMENDACAO_ID NUMBER(10) NOT NULL,
  USER_ID         NUMBER(10) NOT NULL,
  TRILHA_ID       NUMBER(10) NOT NULL,
  SCORE           NUMBER(5,2),
  CREATED_AT      DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_RECOMENDACAO IS 'Recomendações de trilhas baseadas em IA';
COMMENT ON COLUMN TB_RECOMENDACAO.RECOMENDACAO_ID IS 'ID da recomendação';
COMMENT ON COLUMN TB_RECOMENDACAO.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_RECOMENDACAO.TRILHA_ID IS 'FK para TB_TRILHA.TRILHA_ID';
COMMENT ON COLUMN TB_RECOMENDACAO.SCORE IS 'Score de relevância da recomendação';
COMMENT ON COLUMN TB_RECOMENDACAO.CREATED_AT IS 'Data da recomendação';

ALTER TABLE TB_RECOMENDACAO ADD CONSTRAINT TB_RECOMENDACAO_PK PRIMARY KEY (RECOMENDACAO_ID);

ALTER TABLE TB_RECOMENDACAO
  ADD CONSTRAINT TB_RECOMENDACAO_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

ALTER TABLE TB_RECOMENDACAO
  ADD CONSTRAINT TB_RECOMENDACAO_TB_TRILHA_FK FOREIGN KEY (TRILHA_ID)
  REFERENCES TB_TRILHA (TRILHA_ID)
;

CREATE OR REPLACE TRIGGER TB_RECOMENDACAO_ID_TRG
BEFORE INSERT ON TB_RECOMENDACAO
FOR EACH ROW
WHEN (NEW.RECOMENDACAO_ID IS NULL)
BEGIN
  :NEW.RECOMENDACAO_ID := TB_RECOMENDACAO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 13: TB_CERTIFICADO (Certificados Emitidos)
-- =========================================================================
CREATE TABLE TB_CERTIFICADO
(
  CERTIFICADO_ID       NUMBER(10) NOT NULL,
  USER_ID              NUMBER(10) NOT NULL,
  TRILHA_ID            NUMBER(10) NOT NULL,
  CODIGO_VERIFICACAO   VARCHAR2(100) UNIQUE NOT NULL,
  DATA_EMISSAO         DATE DEFAULT SYSDATE NOT NULL,
  VALIDADE_ATE         DATE
)
;

COMMENT ON TABLE TB_CERTIFICADO IS 'Certificados de conclusão de trilhas';
COMMENT ON COLUMN TB_CERTIFICADO.CERTIFICADO_ID IS 'ID do certificado';
COMMENT ON COLUMN TB_CERTIFICADO.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_CERTIFICADO.TRILHA_ID IS 'FK para TB_TRILHA.TRILHA_ID';
COMMENT ON COLUMN TB_CERTIFICADO.CODIGO_VERIFICACAO IS 'Código único para verificação';
COMMENT ON COLUMN TB_CERTIFICADO.DATA_EMISSAO IS 'Data de emissão do certificado';
COMMENT ON COLUMN TB_CERTIFICADO.VALIDADE_ATE IS 'Data de validade (se aplicável)';

ALTER TABLE TB_CERTIFICADO ADD CONSTRAINT TB_CERTIFICADO_PK PRIMARY KEY (CERTIFICADO_ID);

ALTER TABLE TB_CERTIFICADO
  ADD CONSTRAINT TB_CERTIFICADO_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

ALTER TABLE TB_CERTIFICADO
  ADD CONSTRAINT TB_CERTIFICADO_TB_TRILHA_FK FOREIGN KEY (TRILHA_ID)
  REFERENCES TB_TRILHA (TRILHA_ID)
;

CREATE OR REPLACE TRIGGER TB_CERTIFICADO_ID_TRG
BEFORE INSERT ON TB_CERTIFICADO
FOR EACH ROW
WHEN (NEW.CERTIFICADO_ID IS NULL)
BEGIN
  :NEW.CERTIFICADO_ID := TB_CERTIFICADO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 14: TB_ACHIEVEMENT (Conquistas/Badges)
-- =========================================================================
CREATE TABLE TB_ACHIEVEMENT
(
  ACHIEVEMENT_ID   NUMBER(10) NOT NULL,
  USER_ID          NUMBER(10) NOT NULL,
  TIPO             VARCHAR2(50) NOT NULL,
  NOME             VARCHAR2(200) NOT NULL,
  DESCRICAO        VARCHAR2(1000),
  ICONE            VARCHAR2(100),
  XP_GANHO         NUMBER(10) DEFAULT 0,
  RARIDADE         VARCHAR2(20),
  DESBLOQUEADO_EM  DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_ACHIEVEMENT IS 'Conquistas/badges dos usuários';
COMMENT ON COLUMN TB_ACHIEVEMENT.ACHIEVEMENT_ID IS 'ID da conquista';
COMMENT ON COLUMN TB_ACHIEVEMENT.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_ACHIEVEMENT.TIPO IS 'Tipo de achievement (TRILHA, SKILL, STREAK, etc)';
COMMENT ON COLUMN TB_ACHIEVEMENT.NOME IS 'Nome da conquista';
COMMENT ON COLUMN TB_ACHIEVEMENT.DESCRICAO IS 'Descrição da conquista';
COMMENT ON COLUMN TB_ACHIEVEMENT.ICONE IS 'Nome/URL do ícone';
COMMENT ON COLUMN TB_ACHIEVEMENT.XP_GANHO IS 'XP ganho ao desbloquear';
COMMENT ON COLUMN TB_ACHIEVEMENT.RARIDADE IS 'Raridade: COMUM, RARO, EPICO, LENDARIO';
COMMENT ON COLUMN TB_ACHIEVEMENT.DESBLOQUEADO_EM IS 'Data de desbloqueio';

ALTER TABLE TB_ACHIEVEMENT ADD CONSTRAINT TB_ACHIEVEMENT_PK PRIMARY KEY (ACHIEVEMENT_ID);

ALTER TABLE TB_ACHIEVEMENT
  ADD CONSTRAINT TB_ACHIEVEMENT_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

CREATE OR REPLACE TRIGGER TB_ACHIEVEMENT_ID_TRG
BEFORE INSERT ON TB_ACHIEVEMENT
FOR EACH ROW
WHEN (NEW.ACHIEVEMENT_ID IS NULL)
BEGIN
  :NEW.ACHIEVEMENT_ID := TB_ACHIEVEMENT_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 15: TB_NOTIFICACAO (Notificações do Sistema)
-- =========================================================================
CREATE TABLE TB_NOTIFICACAO
(
  NOTIFICACAO_ID NUMBER(10) NOT NULL,
  USER_ID        NUMBER(10) NOT NULL,
  TIPO           VARCHAR2(50) NOT NULL,
  TITULO         VARCHAR2(300) NOT NULL,
  MENSAGEM       VARCHAR2(2000),
  ICONE          VARCHAR2(100),
  LINK           VARCHAR2(500),
  LIDA           NUMBER(1) DEFAULT 0,
  CRIADO_EM      DATE DEFAULT SYSDATE NOT NULL
)
;

COMMENT ON TABLE TB_NOTIFICACAO IS 'Notificações enviadas aos usuários';
COMMENT ON COLUMN TB_NOTIFICACAO.NOTIFICACAO_ID IS 'ID da notificação';
COMMENT ON COLUMN TB_NOTIFICACAO.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_NOTIFICACAO.TIPO IS 'Tipo: INFO, ALERTA, ACHIEVEMENT, etc';
COMMENT ON COLUMN TB_NOTIFICACAO.TITULO IS 'Título da notificação';
COMMENT ON COLUMN TB_NOTIFICACAO.MENSAGEM IS 'Mensagem completa';
COMMENT ON COLUMN TB_NOTIFICACAO.ICONE IS 'Ícone da notificação (ex: Sparkles, Award)';
COMMENT ON COLUMN TB_NOTIFICACAO.LINK IS 'Link para ação relacionada';
COMMENT ON COLUMN TB_NOTIFICACAO.LIDA IS 'Flag se foi lida (0=não, 1=sim)';
COMMENT ON COLUMN TB_NOTIFICACAO.CRIADO_EM IS 'Data de criação';

ALTER TABLE TB_NOTIFICACAO ADD CONSTRAINT TB_NOTIFICACAO_PK PRIMARY KEY (NOTIFICACAO_ID);

ALTER TABLE TB_NOTIFICACAO
  ADD CONSTRAINT TB_NOTIFICACAO_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

CREATE OR REPLACE TRIGGER TB_NOTIFICACAO_ID_TRG
BEFORE INSERT ON TB_NOTIFICACAO
FOR EACH ROW
WHEN (NEW.NOTIFICACAO_ID IS NULL)
BEGIN
  :NEW.NOTIFICACAO_ID := TB_NOTIFICACAO_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- TABELA 16: TB_META (Metas de Aprendizado)
-- =========================================================================
CREATE TABLE TB_META
(
  META_ID         NUMBER(10) NOT NULL,
  USER_ID         NUMBER(10) NOT NULL,
  TITULO          VARCHAR2(300) NOT NULL,
  DESCRICAO       VARCHAR2(2000),
  TIPO            VARCHAR2(50),
  TARGET_VALUE    NUMBER(10) NOT NULL,
  CURRENT_VALUE   NUMBER(10) DEFAULT 0,
  UNIDADE         VARCHAR2(50),
  DATA_INICIO     DATE DEFAULT SYSDATE NOT NULL,
  DATA_FIM        DATE,
  PRAZO           DATE,
  STATUS          VARCHAR2(50) DEFAULT 'EM_ANDAMENTO'
)
;

COMMENT ON TABLE TB_META IS 'Metas de aprendizado dos usuários';
COMMENT ON COLUMN TB_META.META_ID IS 'ID da meta';
COMMENT ON COLUMN TB_META.USER_ID IS 'FK para TB_USER.USER_ID';
COMMENT ON COLUMN TB_META.TITULO IS 'Título da meta';
COMMENT ON COLUMN TB_META.DESCRICAO IS 'Descrição detalhada';
COMMENT ON COLUMN TB_META.TIPO IS 'Tipo da meta: TRILHA, XP, MODULO, TEMPO';
COMMENT ON COLUMN TB_META.TARGET_VALUE IS 'Valor alvo da meta';
COMMENT ON COLUMN TB_META.CURRENT_VALUE IS 'Valor atual/progresso';
COMMENT ON COLUMN TB_META.UNIDADE IS 'Unidade (horas, trilhas, módulos, etc)';
COMMENT ON COLUMN TB_META.DATA_INICIO IS 'Data de início';
COMMENT ON COLUMN TB_META.DATA_FIM IS 'Data limite para conclusão';
COMMENT ON COLUMN TB_META.PRAZO IS 'Data prazo final (alias para DATA_FIM)';
COMMENT ON COLUMN TB_META.STATUS IS 'Status: EM_ANDAMENTO, CONCLUIDA, CANCELADA';

ALTER TABLE TB_META ADD CONSTRAINT TB_META_PK PRIMARY KEY (META_ID);

ALTER TABLE TB_META
  ADD CONSTRAINT TB_META_TB_USER_FK FOREIGN KEY (USER_ID)
  REFERENCES TB_USER (USER_ID)
;

CREATE OR REPLACE TRIGGER TB_META_ID_TRG
BEFORE INSERT ON TB_META
FOR EACH ROW
WHEN (NEW.META_ID IS NULL)
BEGIN
  :NEW.META_ID := TB_META_ID_SEQ.NEXTVAL;
END;
/

-- =========================================================================
-- ÍNDICES PARA PERFORMANCE
-- =========================================================================
CREATE INDEX IDX_USER_EMAIL ON TB_USER(EMAIL);
CREATE INDEX IDX_USER_XP ON TB_USER(XP);
CREATE INDEX IDX_USER_LEVEL ON TB_USER(LEVEL_ACCOUNT);
CREATE INDEX IDX_TRILHA_CATEGORIA ON TB_TRILHA(CATEGORIA);
CREATE INDEX IDX_TRILHA_RATING ON TB_TRILHA(RATING);
CREATE INDEX IDX_INSCRICAO_USER_TRILHA ON TB_INSCRICAO(USER_ID, TRILHA_ID);
CREATE INDEX IDX_PROGRESSO_INSCRICAO ON TB_PROGRESSO(INSCRICAO_ID);
CREATE INDEX IDX_OPORTUNIDADE_EMPRESA ON TB_OPORTUNIDADE(EMPRESA_ID);
CREATE INDEX IDX_OPORTUNIDADE_STATUS ON TB_OPORTUNIDADE(STATUS);
CREATE INDEX IDX_TRILHA_OPP_TRILHA ON TB_TRILHA_OPORTUNIDADE(TRILHA_ID);
CREATE INDEX IDX_TRILHA_OPP_OPORT ON TB_TRILHA_OPORTUNIDADE(OPORTUNIDADE_ID);
CREATE INDEX IDX_CERTIFICADO_USER ON TB_CERTIFICADO(USER_ID);
CREATE INDEX IDX_ACHIEVEMENT_USER ON TB_ACHIEVEMENT(USER_ID);
CREATE INDEX IDX_ACHIEVEMENT_TIPO ON TB_ACHIEVEMENT(TIPO);
CREATE INDEX IDX_NOTIFICACAO_USER_LIDA ON TB_NOTIFICACAO(USER_ID, LIDA);
CREATE INDEX IDX_META_USER_STATUS ON TB_META(USER_ID, STATUS);

-- =========================================================================
-- VIEWS ANALÍTICAS
-- =========================================================================

-- View de usuários com estatísticas completas
CREATE OR REPLACE VIEW VW_USER_STATS AS
SELECT
  u.USER_ID,
  u.NAME,
  u.EMAIL,
  u.XP,
  u.LEVEL_ACCOUNT,
  u.STREAK_DIAS,
  COUNT(DISTINCT i.INSCRICAO_ID) AS TOTAL_INSCRICOES,
  COUNT(DISTINCT CASE WHEN i.DATA_CONCLUSAO IS NOT NULL THEN i.INSCRICAO_ID END) AS TRILHAS_COMPLETAS,
  COUNT(DISTINCT p.PROGRESSO_ID) AS TOTAL_MODULOS_PROGRESSO,
  COUNT(DISTINCT CASE WHEN p.PERCENTAGE = 100 THEN p.PROGRESSO_ID END) AS MODULOS_COMPLETOS,
  COUNT(DISTINCT c.CERTIFICADO_ID) AS TOTAL_CERTIFICADOS,
  COUNT(DISTINCT a.ACHIEVEMENT_ID) AS TOTAL_ACHIEVEMENTS
FROM TB_USER u
LEFT JOIN TB_INSCRICAO i ON u.USER_ID = i.USER_ID
LEFT JOIN TB_PROGRESSO p ON i.INSCRICAO_ID = p.INSCRICAO_ID
LEFT JOIN TB_CERTIFICADO c ON u.USER_ID = c.USER_ID
LEFT JOIN TB_ACHIEVEMENT a ON u.USER_ID = a.USER_ID
GROUP BY u.USER_ID, u.NAME, u.EMAIL, u.XP, u.LEVEL_ACCOUNT, u.STREAK_DIAS;

-- View de trilhas com estatísticas
CREATE OR REPLACE VIEW VW_TRILHA_STATS AS
SELECT
  t.TRILHA_ID,
  t.TITLE,
  t.CATEGORIA,
  t.DIFFICULTY,
  t.RATING,
  t.TOTAL_AVALIACOES,
  COUNT(DISTINCT tm.MODULO_ID) AS TOTAL_MODULOS,
  COUNT(DISTINCT i.INSCRICAO_ID) AS TOTAL_INSCRICOES,
  COUNT(DISTINCT CASE WHEN i.DATA_CONCLUSAO IS NOT NULL THEN i.INSCRICAO_ID END) AS TOTAL_CONCLUSOES,
  CASE
    WHEN COUNT(DISTINCT i.INSCRICAO_ID) > 0 THEN
      ROUND(COUNT(DISTINCT CASE WHEN i.DATA_CONCLUSAO IS NOT NULL THEN i.INSCRICAO_ID END) * 100.0 / COUNT(DISTINCT i.INSCRICAO_ID), 2)
    ELSE 0
  END AS TAXA_CONCLUSAO,
  COUNT(DISTINCT to_rel.OPORTUNIDADE_ID) AS TOTAL_VAGAS_VINCULADAS
FROM TB_TRILHA t
LEFT JOIN TB_TRILHA_MODULO tm ON t.TRILHA_ID = tm.TRILHA_ID
LEFT JOIN TB_INSCRICAO i ON t.TRILHA_ID = i.TRILHA_ID
LEFT JOIN TB_TRILHA_OPORTUNIDADE to_rel ON t.TRILHA_ID = to_rel.TRILHA_ID
GROUP BY t.TRILHA_ID, t.TITLE, t.CATEGORIA, t.DIFFICULTY, t.RATING, t.TOTAL_AVALIACOES;

-- View de oportunidades com informações completas
CREATE OR REPLACE VIEW VW_OPORTUNIDADES_COMPLETAS AS
SELECT
  o.OPORTUNIDADE_ID,
  o.TITLE AS VAGA_TITULO,
  o.DESCRIPTION AS VAGA_DESCRICAO,
  o.SALARIO_MIN,
  o.SALARIO_MAX,
  o.NIVEL,
  o.LOCALIZACAO,
  o.TIPO_CONTRATO,
  o.STATUS AS VAGA_STATUS,
  o.POSTED_AT,
  e.EMPRESA_ID,
  e.NAME AS EMPRESA_NOME,
  e.WEBSITE AS EMPRESA_WEBSITE,
  COUNT(DISTINCT to_rel.TRILHA_ID) AS TOTAL_TRILHAS_VINCULADAS
FROM TB_OPORTUNIDADE o
JOIN TB_EMPRESA e ON o.EMPRESA_ID = e.EMPRESA_ID
LEFT JOIN TB_TRILHA_OPORTUNIDADE to_rel ON o.OPORTUNIDADE_ID = to_rel.OPORTUNIDADE_ID
GROUP BY o.OPORTUNIDADE_ID, o.TITLE, o.DESCRIPTION, o.SALARIO_MIN, o.SALARIO_MAX,
         o.NIVEL, o.LOCALIZACAO, o.TIPO_CONTRATO, o.STATUS, o.POSTED_AT,
         e.EMPRESA_ID, e.NAME, e.WEBSITE;

-- =========================================================================
-- FIM DO DDL COMPLETO
-- =========================================================================

COMMIT;
